package projectEuler;
/**
 * "Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms."
 * 
 * 
 * @author Diego (DRA2840)
 */
public class P002 {
	
	private static final int MAX = 4000000;
	
	public static void main(String[] args) {
		
		System.out.println( sumOfEvenFibonacciNumbers(0, 0, 1) );
		
	}
	
	/**
	 * Sums all even Fibonacci numbers below the constant MAX (included)
	 * @param sum the sum so far
	 * @param last the last fibonacci number calculated
	 * @param actual the actual fibonacci number
	 * @return The sum of all even Fibonacci numbers until MAX (four million)
	 */
	private static int sumOfEvenFibonacciNumbers (int sum, int last, int actual){
		if(actual > MAX){
			return sum;
		}
		return sumOfEvenFibonacciNumbers( ((isEven(actual))? sum+actual : sum), actual, actual + last );
	}
	
	private static boolean isEven(int a){
		return  a%2 == 0 ;
	}

}
