package projectEuler;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers. 
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers: 
 *    1: 1
 *    3: 1,3 
 *    6: 1,2,3,6
 *    10: 1,2,5,10
 *    15: 1,3,5,15
 *    21: 1,3,7,21
 *    28: 1,2,4,7,14,28
 *    
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 * 
 * @author Diego (DRA2840)
 *
 */
public class P012 {
	
	public static void main(String[] args) {
		System.out.println(firstTriangleNumberToHaveXDivisorsNonRecursive(500));
		System.out.println(firstTriangleNumberToHaveXDivisors(1,2,5));
	}
	
	public static long firstTriangleNumberToHaveXDivisorsNonRecursive(int numberOfDivisors) {
		long numberToTest = 1;
		int aux = 2;
		while(numerOfDivisors(numberToTest, 0, 1) < numberOfDivisors){
			numberToTest +=aux;
			++aux;
		}
		return numberToTest;
	}
	
	public static long firstTriangleNumberToHaveXDivisors(long numberToTest, int aux, int numberOfDivisors){
		if(numerOfDivisors(numberToTest, 0, 1)< numberOfDivisors){
			return firstTriangleNumberToHaveXDivisors(numberToTest + aux, ++aux, numberOfDivisors);
		}
		
		return numberToTest;
	}
	
	public static int numerOfDivisors(long number, int aux, int i){
		if(i*i > number){
			return aux;
		}else if(i*i == number){
			return aux+1;
		}
	
		return numerOfDivisors(number, isDivisor(i, number)?aux+2:aux, ++i);
	}

	private static boolean isDivisor(int i, long number) {
		return number%i==0;
	}

}
